version: "3"
services:
  web:
    restart: always
    build:
      context: .
    volumes:
      - .:/app
    command: sh -c "rm -f tmp/pids/server.pid && ./bin/dev"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DB_USERNAME: "htkr_dev"
      DB_PASSWORD: "password0!"
  db:
    restart: always
    image: mysql:8.0.27
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: "htkr"
      MYSQL_USER: "htkr_dev"
      MYSQL_ROOT_PASSWORD: "p@ssw0rd"
      MYSQL_PASSWORD: "password0!"
      TZ: "Asia/Tokyo"
      MYSQL_ROOT_HOST: "%"
    tty: true
    command: mysqld --character-set-server=utf8mb4 --explicit_defaults_for_timestamp=true --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
